### ISSUE TITLE
GWT 2.8 compatibility?

### ISSUE THREAD

**Issue by bvollmerOT** [laaglu/lib-gwt-svg#16]
Hi,
I have a project which makes use of lib-gwt-svg to include SVG images as a SVGResource. To check GWT 2.8 compatiblity of the project I compiled against a trunk version build of GWT 2.8. It seems that lib-gwt-svg causes an issue: If I replace my SVGResources with ImageResource ones, it compiles successfully. But the compiler stacktrace is not very obvious, so I'm unsure if my problem is really related to lib-gwt-svg.

Can someone confirm if version 0.5.10 is compatible with GWT 2.8.0 or not?

**Comment by laaglu** [comment]
I will address this when 2.8.0 nears completion (when a RC becomes available)

**Comment by svenefftinge** [comment]
I see you did the necessary changes in https://github.com/laaglu/lib-gwt-svg/commit/8a08ee986ad933aa39748f2fa0ec287c37b313f3. Could you do a beta release?

**Comment by laaglu** [comment]
It seems 2.8.0-RC1 is about to be released in a few days (see https://github.com/gwtproject/gwt-site/pull/181). I will do a release when it is

**Comment by danielfornies** [comment]
Hi, was that release done? We're now at GWT 2.8 RC3, and I still have issues with what seems to be an imcompatible override of UiBinderWriter with lib-gwt-svg 0.5.11. Is there any version I can use to fix this?

**Comment by danielkaneider** [comment]
GWT 2.8 final was recently published to maven central. When can we expect a new version of lib-gwt-svg?

**Comment by laaglu** [comment]
Soon. Waiting for final gwt-maven-plugin (current version is still 2.8.0-rc3)

**Comment by jayshin** [comment]
Now the final version 2.8.0 is in the maven central repository. Eager to the updated version soon.

**Comment by laaglu** [comment]
Done. Should reach maven-central tomorrow
