### ISSUE TITLE
SaxParse error and illegal char exceptions

### ISSUE THREAD

**Issue by tommueller** [laaglu/lib-gwt-svg#19]
I'm having a double issue with this lib.

The first problem (and maybe also cause of the second one) is that no svg passes the validation. I get 

> [ERROR] Invalid SVG input @file:/workspace/project/src/com/company/client/utils/gui/icons/pages/filename.svg L:1,C:1
  org.xml.sax.SAXParseException; systemId: file:/workspace/project/src/com/client/utils/gui/icons/pages/filename.svg; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

This happens both with our original files, having a header like this:
> <?xml version="1.0" encoding="utf-8"?>
  <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">`

but also with a testfile https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg

**All** of the files pass the validation at https://validator.w3.org/

If I bruteforce add `@Validated(validated = true)` to all the entries in my ImageBundle so that they look like this:

> 	@Source("icons/pages/filename.svg")
	@Validated(validated = false)
	SVGResource pageFilenameIcon();

I can compile the project but get a JS error (printed to the browser console) which reads like this:

> InvalidCharacterError:
  String contains an invalid character

which comes from here:

> base64encode_0_g$()
getSafeUri_6_g$()

After all I cannot use the library at all .. What could be the problem? I have the jar included and inherit it with `<inherits name='org.vectomatic.libgwtsvg'/>`

Any ideas? Thanks!
Tom

**Comment by laaglu** [comment]
Could it be a problem of byte order mark at the beginning of the file ?

**Comment by tommueller** [comment]
Okay I fixed this. I ran svg-cleaner over all the SVGs, apparently the W3C-validator is less strict then the one in here ...
