### ISSUE TITLE
DashArrayParser depends from html-unit (broken compilation as result)

### ISSUE THREAD

**Issue by turansky** [laaglu/lib-gwt-svg#23]
If vectomatic inherited in Client.gwt.xml (has EntryPoint) and other module override (inherit) module Client, than it wil be broken with error `Couldn't found CSSPrimitiveValue`.

Error reproduced on version 0.5.12 with GWT 2.8.
On version 0.5.10 with GWT 2.7 no such problem.

**Comment by laaglu** [comment]
Probably a case of involuntary import auto-completion with Eclipse. Clearly there should be no dependency on html-unit (the intent was just to import a bunch of constants, which actually should come from OMCSSPrimitiveValue I think). Will fix that soon

**Comment by turansky** [comment]
Thanks in advance.

**Comment by turansky** [comment]
When it will be released?
It will be version 0.5.13?

**Comment by laaglu** [comment]
Yes it will be version 0.5.13 and will require the just released gwt-2.8.1. That should be in about 2 weeks, more or less (my build server had a hardware failure, I am waiting for the new motherboard)

**Comment by turansky** [comment]
Any news about release?

Thanks in advance.

**Comment by laaglu** [comment]
finally got my motherboard back from supermicro ! Getting started on the release, should be there by the end of the week

**Comment by laaglu** [comment]
The release for gwt-2.8.1 is not available on maven central and https://vectomatic.org/

**Comment by turansky** [comment]
Thank you.
