### ISSUE TITLE
Is 0.5.13 compatible with GWT 2.8.2

### ISSUE THREAD

**Issue by srkprasadam** [laaglu/lib-gwt-svg#25]
GWT released 2.8.2 on Oct 19, 2017. Is the latest lib-gwt-svg version 0.5.13 compatible with GWT 2.8.2 ?

**Comment by laaglu** [comment]
I have not had time to check yet. I will make some tests and answer your question soon

**Comment by laaglu** [comment]
I have created a new build (0.5.14) for GWT 2.8.2. It should be in maven central tomorrow. I think the 0.5.13 jar ought to work with 2.8.2 but from a maven point of view it is better to have a dedicated build
