### ISSUE TITLE
SVG 2 support

### ISSUE THREAD

**Issue by mayjs** [laaglu/lib-gwt-svg#27]
Firefox has recently removed some features that are not included in SVG2 anymore.
One of these features is the SVGPathSeg-API, which is heavily used by this library right now.
See the [Firefox Bugtracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1441233) for more details.

A [polyfill](https://github.com/progers/pathseg/blob/master/pathseg.js) based on the original Chromium implementation for this API is available. I think we could possibly just bundle this polyfill with the library.

**Comment by laaglu** [comment]
Thanks for reporting the problem. I have fixed it already, see https://github.com/laaglu/lib-gwt-svg/issues/26 and lib-gwt-svg-0.5.15

**Comment by mayjs** [comment]
Sorry for the duplicate I didn't realize that there was a recent commit to the library. Thanks for the immediate reaction!
